### PR TITLE
Moved to `gmusic.js` name and `GMusic` constructor

### PR DESCRIPTION
**Pull request by twolfson**
We have renamed our repository and organization. As a result, there are a lot of items to rename. In this PR:
- Updated `twolfson/google-music.js` to `gmusic-utils/gmusic.js`
- Updated `GoogleMusic` constructor to `GMusic`
- Updated `googleMusic` instance to `gmusic`
- Updated `google-music` repository name to `gmusic.js`
- Added "Not affiliated with Google Inc" notice to README

/cc @gmusic-utils/gmusic-js

### CODE REVIEW

**Comment by twolfson** [comment]
Note to anyone curious, I'm pretty confident we found all of the committed files by leveraging:

``` bash
git grep -i google
git grep -i twolfson
```

**Comment by twolfson** [comment]
Bump on this PR since it's blocking other future upcoming releases =/

/cc @MarshallOfSound (since you seem to be online)

**Comment by MarshallOfSound** [comment]
I've done a global find through my local copy and as far as I can see all instances appear to have been renamed.

LGTM :+1:

**Comment by jacobwgillespie** [comment]
LGTM

**Comment by twolfson** [comment]
Going to :shipit:

**Comment by twolfson** [comment]
We are live on `npm` :tada: 

https://www.npmjs.com/package/gmusic.js

**Pull request merged**
