### PR TITLE
Wrote notice for npm about rename

### PR DESCRIPTION
**Pull request by twolfson**
With our repository rename, it is a good courtesy to post a notice to `npm` about the rename. This PR is a preview of what will be posted to `npm`.

**This will not be landed to `master`.**

The README can be viewed at https://github.com/gmusic-utils/gmusic.js/tree/819f3417f2bb10110ed9c13eb0d43326a6adb985

In this PR:
- Removed all non-documentation files
- Updated README to document rename

/cc @gmusic-utils/gmusic-js

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
LGTM

**Comment by MarshallOfSound** [comment]
We should use the `npm deprecate` CLI command as well.

https://docs.npmjs.com/cli/deprecate

**Comment by twolfson** [comment]
Cool, going to wait until #24 is approved and we are published to `npm`/`bower` before publishing this notice =)

**Comment by twolfson** [comment]
This has been published to `npm` :tada:

**Pull request closed without merging**
