### PR TITLE
Update the title and albumArt selectors to match googles changes Fixes #14

### LINKED ISSUE #14: Title and album art are not fetched correctly
Google recently changed the ID's and classes on the album art and song title elements.  The change is indicated below  
`#player-song-title` became `#currently-playing-title`
`#playingAlbumArt` became `#playerBarArt`

The fix in my JS  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/9705ef6e213ef924108ce75f8b39279db7cbda6c

### PR DESCRIPTION
**Pull request by MarshallOfSound**

### CODE REVIEW

**Comment by twolfson** [comment]
Looks good, landing now. In the future, please add a little more substance to the description itself (e.g. providing a link to #14 so there is a cross-reference that GitHub shows).

An example description I would provide:

``` md
In #14, we noticed that the title and album art selectors are broken. We have resolved that in `MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-`. This PR pulls over those changes. In this PR:

- Patched title and album art selectors
- Fixes #14
```

**Comment by MarshallOfSound** [comment]
Yep, wasn't quite sure what to put in the description so left it blank, will follow that guide in future :cactus:

**Comment by twolfson** [comment]
Verified test went from red to green :tada:

**Comment by twolfson** [comment]
This has been merged/published in `3.3.1` :shipit:

**Pull request merged**
