### PR TITLE
Fixed the documentation of the `playback-time` event

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Simple fix but the incorrect docs through me for a loop for a few minutes :100: :cactus: 

/cc @gmusic-utils/gmusic-js

### CODE REVIEW

**Comment by twolfson** [comment]
Nice catch. Looks good to me :+1:

**Comment by chrismou** [comment]
:+1:

**Comment by twolfson** [comment]
@MarshallOfSound Please update the CHANGELOG and run a patch release; we will prob want to update the documentation in `npm` as well (releasing is how we do that)

**Comment by twolfson** [comment]
Release process documentation: https://github.com/gmusic-utils/gmusic.js/blob/4.0.3/CONTRIBUTING.md#release-process

**Comment by MarshallOfSound** [comment]
Yep, was mucking around with foundry, it doesn't seem to work on windows so I had to set up the project on my work laptop.

**Comment by twolfson** [comment]
Ah, damn. I thought we got all the Windows kinks worked out =(

**Comment by MarshallOfSound** [comment]
Could be something to do with my funky npm install, but idk.  Hopefully won't be releasing too many times :+1:

**Comment by twolfson** [comment]
As a heads up, I'm deleting this branch (as well as all of mine that I forgot to delete)

**Pull request merged**
