### PR TITLE
Port library to ES6 with Babel

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Simple direct ES6 port from around 20 minutes of work.  Contributes to the discussion at #47, and there are more comments there.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Note that if we like this idea, the tests could be ported as well.  Keeping this PR simple for the initial review.

**Comment by jostrander** [comment]
Pending all tests passing this LGTM

**Comment by twolfson** [comment]
This only further confirms my sentiments from #47. There are no technical benefits to changes like those in the PR; they are stylistic, just as transitioning to CoffeeScript would have been back in the day.

**Comment by jacobwgillespie** [comment]
They aren't just stylistic, we're getting immutability checks with `let` / `const` and native language binding with arrow functions.  (and better named functions in the build, though we could add those manually if we wanted)

I'll add some more comments to #47.

**Comment by twolfson** [comment]
While we are going to fork, I wrote down some counter arguments on Friday that I would hate to see gone to waste:
- We are trying to create problems that we don't have
  - We don't have a problem with mutability; all functions are short and interact with the directly DOM
  - Automatically named functions are only for arrow functions; there are still long form functions which should be named. For that, we should use a tool like JSCS (not sure if ESLint received a port of the rule from there) but we haven't had this problem either
    -  Also arrow functions get performance hit from using `.bind` =/

**Pull request closed without merging**
