### PR TITLE
Allow volume to be smoothly transitioned from original volume to a new volume

### PR DESCRIPTION
**Pull request by MarshallOfSound**
This does not modify existing functionality buts the ability for the `setVolume`, `increaseVolume` and `decreaseVolume` calls to smoothly transition between the current volume and the target volume.

Gives a much better user experience than a sudden jump from 0 -> 80

/cc @gmusic-utils/gmusic-js

### CODE REVIEW

**Comment by twolfson** [comment]
While I understand the reasoning, I don't think this belongs in the repo. `gmusic.js` is focused on low level controls whereas tweening `setVolume` calls can be done by a higher level library. Additionally, there are lots of ways to tween which we shouldn't dictate. For example:

https://github.com/mattdesl/eases

As an alternative, maybe we could place an example in the README?

**Comment by MarshallOfSound** [comment]
OK, if I took out the smooth controls would you accept the PR based on the new syntax used to modify the volume.  The old syntax only changed the volume in increments of 5, the new syntax allows you to arbitrallily set values regardless of the current `step` value.

The new syntax is requried to make smoothing like this work

**Comment by twolfson** [comment]
The increments of 5 were due to restrictions by Google Music's own UI:

``` js
> $('#material-vslider')
<paper-slider id="material-vslider" min="0" max="100" step="5" title="Volume" role="slider" tabindex="0" aria-disabled="false" value="95" aria-valuemin="0" aria-valuemax="100" aria-valuenow="95" class="x-scope paper-slider-1">
> $('#material-vslider').value
95
> $('#material-vslider').decrement()
undefined
> $('#material-vslider').value
90
> $('#material-vslider').value = 97
97
> $('#material-vslider').value
95
```

I see the issue you are talking about (e.g. `increaseVolume(1)` twice would cause a volume increase of `10`). However, I don't think we can adjust our internals to handle that:
- We could round up to 5 as Google Music already does but that doesn't solve the problem
- We could add a get/add/round/set to our logic might lead to unexpected behavior (e.g. people might expect Google Music behavior)
- We could add an internal variable for the volume but that is brittle as the user could change it easily

Maybe the tween should perform its own rounding to modulo 5?

**Comment by twolfson** [comment]
Ah, sorry. It took a second for it to click for me. Yea, I would be down to move to using `value =` instead of our `for` loop implementation :+1:

**Comment by twolfson** [comment]
What was the reason for closing this?

**Comment by MarshallOfSound** [comment]
The PR got bloated a bit and the original intent was denied and needed to be changed.  I'll be making a cleaner PR shortly with just the move to `.value`

**Pull request closed without merging**
